name: Deploy landing zone to Azure

on:
  push:
    branches:
      - dev
      - qa
      - stage
      - main

env:
  ENV: ${{ github.ref_name }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate backend
        run: envsubst < IaC/backend-template.conf > IaC/backend.conf

      - name: Setup Terraform
        uses: hashicorp/setup-terraform
      
      - name: Init Terraform
        working-directory: IaC
        run: terraform init -backend-config=backend.conf
      
      - name: Plan
        working-directory: IaC
        run: terraform plan -var="env=${{ env.ENV }}"

